S03 us02 new id bis
WildCodeSchool/orleans-js-0920-p2-secret-bar pull request #37
Opened 2020-11-12 20:16 UTC by THETIGERSEYES

2020-11-12 20:54 UTC, Tibo-Wild approved these changes
Read and approved

2020-11-13 07:26 UTC, ldupas requested changes
Petits soucis d'indentation css pour la validation et ok

2020-11-13 07:26 UTC, ldupas commented on src/components/pages/new-id/NewId.css
> +position: relative;
souci d'indentation sur certains blocs :

2020-11-13 07:26 UTC, ldupas commented on src/components/pages/new-id/NewId.css
> +transform: translate(0 -100%);
-------

2020-11-13 07:26 UTC, ldupas commented on src/components/pages/Home.css
> +width: 150px;
indentation

2020-11-13 07:26 UTC, ldupas commented on src/components/pages/Home.css
> +text-align: center;
jusque ici

2020-11-13 07:26 UTC, ldupas commented on src/components/pages/new-id/NewId.css
> +width: 100%;
ici

2020-11-13 07:26 UTC, ldupas commented on src/components/pages/new-id/NewId.css
> +}
jusqu'ici

2020-11-13 07:26 UTC, ldupas commented on src/components/pages/new-id/NewId.css
> +transform: translate(0 -100%);
jusqu'ici

2020-11-13 08:32 UTC, closed without merging