modification db, fix errorForm and add filter alcool
WildCodeSchool/orleans-js-0920-p2-secret-bar pull request #50
Opened 2020-11-23 16:47 UTC by TheoAt

2020-11-23 16:59 UTC, THETIGERSEYES approved these changes

2020-11-24 07:30 UTC, ldupas requested changes

2020-11-24 07:30 UTC, ldupas commented on src/components/selection/Selection.jsx
>                  <SectionTitle title="Séléction du Jour" color="black"/>
Sélection du jour*

2020-11-24 11:03 UTC, THETIGERSEYES approved these changes

2020-11-24 11:03 UTC, THETIGERSEYES approved these changes

2020-11-24 14:49 UTC, ldupas approved these changes

2020-11-24 14:49 UTC, merged