S03 us11 livred or
WildCodeSchool/orleans-js-0920-p2-secret-bar pull request #51
Opened 2020-11-24 15:38 UTC by jordyngoma

livre d'or present, sans ressponsives design.

2020-11-24 16:18 UTC, THETIGERSEYES approved these changes

2020-11-25 09:21 UTC, ldupas requested changes

2020-11-25 09:21 UTC, ldupas commented on src/components/livreDor/Opinion.jsx
> +      commentaire: 'La soirée était formidable',
comment à la place de commentaire

2020-11-25 09:21 UTC, ldupas commented on src/components/livreDor/Portefolio.css
> +
un saut à la ligne entre chaque sélecteur pour harmoniser

2020-11-25 09:21 UTC, ldupas commented on src/App.jsx
> +import Portefolio from './components/livreDor/Portefolio'
Portfolio pour le composant
visitorsbook pour le dossier

2020-11-25 14:11 UTC, ldupas approved these changes

2020-11-25 14:11 UTC, merged